articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path('', views.articles_list, name="list"),
    path('<slug>', views.articles_detail, name="detail")
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', views.home),
    path('articles/', include('articles.urls'))
]

urlpatterns += staticfiles_urlpatterns()

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + ' ...'

articles/views.py
from django.shortcuts import render, HttpResponse
from . import models

def articles_list(request):
    articles = models.Article.objects.all().order_by('date')
    args = {'articles': articles}
    return render(request, 'articles/articleslist.html', args)

def articles_detail(request, slug):
    return HttpResponse(slug)

djangoBlog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def home(request):
    # return HttpResponse('Home')
    return render(request, 'Home.html')
    
def about(request):
    # return HttpResponse('Hi There, I am Kiarash')س
    return render(request, 'about.html')

articles/templates/articles/articleslist.html
{%extends 'base.html'%}

{%block title%}
Articles
{%endblock%}

{%block content%}
<div class="container">
  <h1>Articles List</h1>
  {% for article in articles %}
  <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
  <p>{{article.snippet}}</p>
  <p>{{article.date}}</p>
  {% endfor %}
</div>
{%endblock%}

templates/Home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <h1>Home</h1>
    <p>Welcome to my Blog</p>
  </body>
</html>

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About</h1>
    <p>ما جنگو رو دوست داریم</p>
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>
      {%block title%}
      Articles
      {%endblock%}
    </title>
  </head>
  <body>
    <h2><a href="{% url 'articles:list' %}">LOGO</a></h2>
    <div class="wrapper">

      {%block content%}

      {%endblock%}

    </div>
  </body>
</html>